/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Model description
    /// </summary>
    [DataContract]
    public partial class CustomerPlanPeriod :  IEquatable<CustomerPlanPeriod>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerPlanPeriod" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="NumberPackPeriodInPlanPeriod">NumberPackPeriodInPlanPeriod.</param>
        /// <param name="TotalInPayment">TotalInPayment.</param>
        public CustomerPlanPeriod(string Id = null, long? NumberPackPeriodInPlanPeriod = null, Dictionary<string, long?> TotalInPayment = null)
        {
            this.Id = Id;
            this.NumberPackPeriodInPlanPeriod = NumberPackPeriodInPlanPeriod;
            this.TotalInPayment = TotalInPayment;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }
        /// <summary>
        /// Gets or Sets NumberPackPeriodInPlanPeriod
        /// </summary>
        [DataMember(Name="numberPackPeriod_inPlanPeriod", EmitDefaultValue=false)]
        public long? NumberPackPeriodInPlanPeriod { get; set; }
        /// <summary>
        /// Gets or Sets TotalInPayment
        /// </summary>
        [DataMember(Name="totalInPayment", EmitDefaultValue=false)]
        public Dictionary<string, long?> TotalInPayment { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomerPlanPeriod {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NumberPackPeriodInPlanPeriod: ").Append(NumberPackPeriodInPlanPeriod).Append("\n");
            sb.Append("  TotalInPayment: ").Append(TotalInPayment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CustomerPlanPeriod);
        }

        /// <summary>
        /// Returns true if CustomerPlanPeriod instances are equal
        /// </summary>
        /// <param name="other">Instance of CustomerPlanPeriod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomerPlanPeriod other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.NumberPackPeriodInPlanPeriod == other.NumberPackPeriodInPlanPeriod ||
                    this.NumberPackPeriodInPlanPeriod != null &&
                    this.NumberPackPeriodInPlanPeriod.Equals(other.NumberPackPeriodInPlanPeriod)
                ) && 
                (
                    this.TotalInPayment == other.TotalInPayment ||
                    this.TotalInPayment != null &&
                    this.TotalInPayment.SequenceEqual(other.TotalInPayment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.NumberPackPeriodInPlanPeriod != null)
                    hash = hash * 59 + this.NumberPackPeriodInPlanPeriod.GetHashCode();
                if (this.TotalInPayment != null)
                    hash = hash * 59 + this.TotalInPayment.GetHashCode();
                return hash;
            }
        }
    }

}
