/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Model description
    /// </summary>
    [DataContract]
    public partial class EmailRecover :  IEquatable<EmailRecover>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailRecover" /> class.
        /// </summary>
        /// <param name="Usr">Usr.</param>
        /// <param name="NewPwd">NewPwd.</param>
        public EmailRecover(string Usr = null, string NewPwd = null)
        {
            this.Usr = Usr;
            this.NewPwd = NewPwd;
        }
        
        /// <summary>
        /// Gets or Sets Usr
        /// </summary>
        [DataMember(Name="usr", EmitDefaultValue=false)]
        public string Usr { get; set; }
        /// <summary>
        /// Gets or Sets NewPwd
        /// </summary>
        [DataMember(Name="newPwd", EmitDefaultValue=false)]
        public string NewPwd { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailRecover {\n");
            sb.Append("  Usr: ").Append(Usr).Append("\n");
            sb.Append("  NewPwd: ").Append(NewPwd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as EmailRecover);
        }

        /// <summary>
        /// Returns true if EmailRecover instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailRecover to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailRecover other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Usr == other.Usr ||
                    this.Usr != null &&
                    this.Usr.Equals(other.Usr)
                ) && 
                (
                    this.NewPwd == other.NewPwd ||
                    this.NewPwd != null &&
                    this.NewPwd.Equals(other.NewPwd)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Usr != null)
                    hash = hash * 59 + this.Usr.GetHashCode();
                if (this.NewPwd != null)
                    hash = hash * 59 + this.NewPwd.GetHashCode();
                return hash;
            }
        }
    }

}
