/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Model description
    /// </summary>
    [DataContract]
    public partial class PricingUiConfPlan :  IEquatable<PricingUiConfPlan>
    {
        /// <summary>
        /// Gets or Sets MainPrice
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MainPriceEnum
        {
            
            /// <summary>
            /// Enum VariableCost for "VariableCost"
            /// </summary>
            [EnumMember(Value = "VariableCost")]
            VariableCost,
            
            /// <summary>
            /// Enum PeriodicCost for "PeriodicCost"
            /// </summary>
            [EnumMember(Value = "PeriodicCost")]
            PeriodicCost,
            
            /// <summary>
            /// Enum Setup for "Setup"
            /// </summary>
            [EnumMember(Value = "Setup")]
            Setup,
            
            /// <summary>
            /// Enum Cost for "Cost"
            /// </summary>
            [EnumMember(Value = "Cost")]
            Cost
        }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PeriodEnum
        {
            
            /// <summary>
            /// Enum Year for "Year"
            /// </summary>
            [EnumMember(Value = "Year")]
            Year,
            
            /// <summary>
            /// Enum Month for "Month"
            /// </summary>
            [EnumMember(Value = "Month")]
            Month,
            
            /// <summary>
            /// Enum Week for "Week"
            /// </summary>
            [EnumMember(Value = "Week")]
            Week,
            
            /// <summary>
            /// Enum Day for "Day"
            /// </summary>
            [EnumMember(Value = "Day")]
            Day
        }

        /// <summary>
        /// Gets or Sets MainPrice
        /// </summary>
        [DataMember(Name="mainPrice", EmitDefaultValue=false)]
        public MainPriceEnum? MainPrice { get; set; }
        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        [DataMember(Name="period", EmitDefaultValue=false)]
        public PeriodEnum? Period { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PricingUiConfPlan" /> class.
        /// </summary>
        /// <param name="MainPrice">MainPrice.</param>
        /// <param name="Id">Id.</param>
        /// <param name="Order">Order.</param>
        /// <param name="IsVisible">IsVisible.</param>
        /// <param name="MainVariableCost">MainVariableCost.</param>
        /// <param name="Period">Period.</param>
        public PricingUiConfPlan(MainPriceEnum? MainPrice = null, string Id = null, int? Order = null, bool? IsVisible = null, string MainVariableCost = null, PeriodEnum? Period = null)
        {
            this.MainPrice = MainPrice;
            this.Id = Id;
            this.Order = Order;
            this.IsVisible = IsVisible;
            this.MainVariableCost = MainVariableCost;
            this.Period = Period;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }
        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name="order", EmitDefaultValue=false)]
        public int? Order { get; set; }
        /// <summary>
        /// Gets or Sets IsVisible
        /// </summary>
        [DataMember(Name="isVisible", EmitDefaultValue=false)]
        public bool? IsVisible { get; set; }
        /// <summary>
        /// Gets or Sets MainVariableCost
        /// </summary>
        [DataMember(Name="mainVariableCost", EmitDefaultValue=false)]
        public string MainVariableCost { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PricingUiConfPlan {\n");
            sb.Append("  MainPrice: ").Append(MainPrice).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  IsVisible: ").Append(IsVisible).Append("\n");
            sb.Append("  MainVariableCost: ").Append(MainVariableCost).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PricingUiConfPlan);
        }

        /// <summary>
        /// Returns true if PricingUiConfPlan instances are equal
        /// </summary>
        /// <param name="other">Instance of PricingUiConfPlan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PricingUiConfPlan other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.MainPrice == other.MainPrice ||
                    this.MainPrice != null &&
                    this.MainPrice.Equals(other.MainPrice)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Order == other.Order ||
                    this.Order != null &&
                    this.Order.Equals(other.Order)
                ) && 
                (
                    this.IsVisible == other.IsVisible ||
                    this.IsVisible != null &&
                    this.IsVisible.Equals(other.IsVisible)
                ) && 
                (
                    this.MainVariableCost == other.MainVariableCost ||
                    this.MainVariableCost != null &&
                    this.MainVariableCost.Equals(other.MainVariableCost)
                ) && 
                (
                    this.Period == other.Period ||
                    this.Period != null &&
                    this.Period.Equals(other.Period)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.MainPrice != null)
                    hash = hash * 59 + this.MainPrice.GetHashCode();
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Order != null)
                    hash = hash * 59 + this.Order.GetHashCode();
                if (this.IsVisible != null)
                    hash = hash * 59 + this.IsVisible.GetHashCode();
                if (this.MainVariableCost != null)
                    hash = hash * 59 + this.MainVariableCost.GetHashCode();
                if (this.Period != null)
                    hash = hash * 59 + this.Period.GetHashCode();
                return hash;
            }
        }
    }

}
