/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Model description
    /// </summary>
    [DataContract]
    public partial class ProductConf :  IEquatable<ProductConf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductConf" /> class.
        /// </summary>
        /// <param name="Resources">Resources.</param>
        /// <param name="Packs">Packs.</param>
        public ProductConf(Dictionary<string, Resource> Resources = null, Dictionary<string, Pack> Packs = null)
        {
            this.Resources = Resources;
            this.Packs = Packs;
        }
        
        /// <summary>
        /// Gets or Sets Resources
        /// </summary>
        [DataMember(Name="resources", EmitDefaultValue=false)]
        public Dictionary<string, Resource> Resources { get; set; }
        /// <summary>
        /// Gets or Sets Packs
        /// </summary>
        [DataMember(Name="packs", EmitDefaultValue=false)]
        public Dictionary<string, Pack> Packs { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductConf {\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  Packs: ").Append(Packs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProductConf);
        }

        /// <summary>
        /// Returns true if ProductConf instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductConf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductConf other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Resources == other.Resources ||
                    this.Resources != null &&
                    this.Resources.SequenceEqual(other.Resources)
                ) && 
                (
                    this.Packs == other.Packs ||
                    this.Packs != null &&
                    this.Packs.SequenceEqual(other.Packs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Resources != null)
                    hash = hash * 59 + this.Resources.GetHashCode();
                if (this.Packs != null)
                    hash = hash * 59 + this.Packs.GetHashCode();
                return hash;
            }
        }
    }

}
