/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerBill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerBillTests
    {
        // TODO uncomment below to declare an instance variable for CustomerBill
        //private CustomerBill instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerBill
            //instance = new CustomerBill();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerBill
        /// </summary>
        [Test]
        public void CustomerBillInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerBill
            //Assert.IsInstanceOfType<CustomerBill> (instance, "variable 'instance' is a CustomerBill");
        }

        /// <summary>
        /// Test the property 'CustomerPlanId'
        /// </summary>
        [Test]
        public void CustomerPlanIdTest()
        {
            // TODO unit test for the property 'CustomerPlanId'
        }
        /// <summary>
        /// Test the property 'CreationTimespan'
        /// </summary>
        [Test]
        public void CreationTimespanTest()
        {
            // TODO unit test for the property 'CreationTimespan'
        }
        /// <summary>
        /// Test the property 'LasUpdateTimespan'
        /// </summary>
        [Test]
        public void LasUpdateTimespanTest()
        {
            // TODO unit test for the property 'LasUpdateTimespan'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalInPayment'
        /// </summary>
        [Test]
        public void TotalInPaymentTest()
        {
            // TODO unit test for the property 'TotalInPayment'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Test]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }

    }

}
