/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerPack
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerPackTests
    {
        // TODO uncomment below to declare an instance variable for CustomerPack
        //private CustomerPack instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerPack
            //instance = new CustomerPack();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerPack
        /// </summary>
        [Test]
        public void CustomerPackInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerPack
            //Assert.IsInstanceOfType<CustomerPack> (instance, "variable 'instance' is a CustomerPack");
        }

        /// <summary>
        /// Test the property 'ClosedTime'
        /// </summary>
        [Test]
        public void ClosedTimeTest()
        {
            // TODO unit test for the property 'ClosedTime'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ResourceStatuList'
        /// </summary>
        [Test]
        public void ResourceStatuListTest()
        {
            // TODO unit test for the property 'ResourceStatuList'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Test]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'ExpirationTimeSpan'
        /// </summary>
        [Test]
        public void ExpirationTimeSpanTest()
        {
            // TODO unit test for the property 'ExpirationTimeSpan'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExactConfId'
        /// </summary>
        [Test]
        public void ExactConfIdTest()
        {
            // TODO unit test for the property 'ExactConfId'
        }
        /// <summary>
        /// Test the property 'PackId'
        /// </summary>
        [Test]
        public void PackIdTest()
        {
            // TODO unit test for the property 'PackId'
        }
        /// <summary>
        /// Test the property 'Spent'
        /// </summary>
        [Test]
        public void SpentTest()
        {
            // TODO unit test for the property 'Spent'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }

    }

}
