/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerPlan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerPlanTests
    {
        // TODO uncomment below to declare an instance variable for CustomerPlan
        //private CustomerPlan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerPlan
            //instance = new CustomerPlan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerPlan
        /// </summary>
        [Test]
        public void CustomerPlanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerPlan
            //Assert.IsInstanceOfType<CustomerPlan> (instance, "variable 'instance' is a CustomerPlan");
        }

        /// <summary>
        /// Test the property 'CurrentBillId'
        /// </summary>
        [Test]
        public void CurrentBillIdTest()
        {
            // TODO unit test for the property 'CurrentBillId'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'EndPeriodToPlanId'
        /// </summary>
        [Test]
        public void EndPeriodToPlanIdTest()
        {
            // TODO unit test for the property 'EndPeriodToPlanId'
        }
        /// <summary>
        /// Test the property 'SwapPlanId'
        /// </summary>
        [Test]
        public void SwapPlanIdTest()
        {
            // TODO unit test for the property 'SwapPlanId'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PackId'
        /// </summary>
        [Test]
        public void PackIdTest()
        {
            // TODO unit test for the property 'PackId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalInPayment'
        /// </summary>
        [Test]
        public void TotalInPaymentTest()
        {
            // TODO unit test for the property 'TotalInPayment'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Test]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'Family'
        /// </summary>
        [Test]
        public void FamilyTest()
        {
            // TODO unit test for the property 'Family'
        }
        /// <summary>
        /// Test the property 'OnExpirePlanId'
        /// </summary>
        [Test]
        public void OnExpirePlanIdTest()
        {
            // TODO unit test for the property 'OnExpirePlanId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

    }

}
