/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GoogleTokenId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GoogleTokenIdTests
    {
        // TODO uncomment below to declare an instance variable for GoogleTokenId
        //private GoogleTokenId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GoogleTokenId
            //instance = new GoogleTokenId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GoogleTokenId
        /// </summary>
        [Test]
        public void GoogleTokenIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GoogleTokenId
            //Assert.IsInstanceOfType<GoogleTokenId> (instance, "variable 'instance' is a GoogleTokenId");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Test]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Exp'
        /// </summary>
        [Test]
        public void ExpTest()
        {
            // TODO unit test for the property 'Exp'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Test]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
        /// <summary>
        /// Test the property 'Iat'
        /// </summary>
        [Test]
        public void IatTest()
        {
            // TODO unit test for the property 'Iat'
        }
        /// <summary>
        /// Test the property 'Sub'
        /// </summary>
        [Test]
        public void SubTest()
        {
            // TODO unit test for the property 'Sub'
        }
        /// <summary>
        /// Test the property 'AtHash'
        /// </summary>
        [Test]
        public void AtHashTest()
        {
            // TODO unit test for the property 'AtHash'
        }
        /// <summary>
        /// Test the property 'Azp'
        /// </summary>
        [Test]
        public void AzpTest()
        {
            // TODO unit test for the property 'Azp'
        }
        /// <summary>
        /// Test the property 'Aud'
        /// </summary>
        [Test]
        public void AudTest()
        {
            // TODO unit test for the property 'Aud'
        }
        /// <summary>
        /// Test the property 'Hd'
        /// </summary>
        [Test]
        public void HdTest()
        {
            // TODO unit test for the property 'Hd'
        }
        /// <summary>
        /// Test the property 'Iss'
        /// </summary>
        [Test]
        public void IssTest()
        {
            // TODO unit test for the property 'Iss'
        }

    }

}
