/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Plan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlanTests
    {
        // TODO uncomment below to declare an instance variable for Plan
        //private Plan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Plan
            //instance = new Plan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Plan
        /// </summary>
        [Test]
        public void PlanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Plan
            //Assert.IsInstanceOfType<Plan> (instance, "variable 'instance' is a Plan");
        }

        /// <summary>
        /// Test the property 'VariableCost'
        /// </summary>
        [Test]
        public void VariableCostTest()
        {
            // TODO unit test for the property 'VariableCost'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OneTimePay'
        /// </summary>
        [Test]
        public void OneTimePayTest()
        {
            // TODO unit test for the property 'OneTimePay'
        }
        /// <summary>
        /// Test the property 'HasVariableCost'
        /// </summary>
        [Test]
        public void HasVariableCostTest()
        {
            // TODO unit test for the property 'HasVariableCost'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Test]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'BeforePlanId'
        /// </summary>
        [Test]
        public void BeforePlanIdTest()
        {
            // TODO unit test for the property 'BeforePlanId'
        }
        /// <summary>
        /// Test the property 'OnExpiratyNextPlanId'
        /// </summary>
        [Test]
        public void OnExpiratyNextPlanIdTest()
        {
            // TODO unit test for the property 'OnExpiratyNextPlanId'
        }
        /// <summary>
        /// Test the property 'UpgradeLevel'
        /// </summary>
        [Test]
        public void UpgradeLevelTest()
        {
            // TODO unit test for the property 'UpgradeLevel'
        }
        /// <summary>
        /// Test the property 'RequirePaymentMethod'
        /// </summary>
        [Test]
        public void RequirePaymentMethodTest()
        {
            // TODO unit test for the property 'RequirePaymentMethod'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PackId'
        /// </summary>
        [Test]
        public void PackIdTest()
        {
            // TODO unit test for the property 'PackId'
        }
        /// <summary>
        /// Test the property 'Typ'
        /// </summary>
        [Test]
        public void TypTest()
        {
            // TODO unit test for the property 'Typ'
        }
        /// <summary>
        /// Test the property 'UiOrder'
        /// </summary>
        [Test]
        public void UiOrderTest()
        {
            // TODO unit test for the property 'UiOrder'
        }
        /// <summary>
        /// Test the property 'Family'
        /// </summary>
        [Test]
        public void FamilyTest()
        {
            // TODO unit test for the property 'Family'
        }
        /// <summary>
        /// Test the property 'UiVisible'
        /// </summary>
        [Test]
        public void UiVisibleTest()
        {
            // TODO unit test for the property 'UiVisible'
        }
        /// <summary>
        /// Test the property 'Withfamily'
        /// </summary>
        [Test]
        public void WithfamilyTest()
        {
            // TODO unit test for the property 'Withfamily'
        }
        /// <summary>
        /// Test the property 'VariableCostWhenPay'
        /// </summary>
        [Test]
        public void VariableCostWhenPayTest()
        {
            // TODO unit test for the property 'VariableCostWhenPay'
        }
        /// <summary>
        /// Test the property 'OneTimePlan'
        /// </summary>
        [Test]
        public void OneTimePlanTest()
        {
            // TODO unit test for the property 'OneTimePlan'
        }

    }

}
