/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PricingTablePlanCost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PricingTablePlanCostTests
    {
        // TODO uncomment below to declare an instance variable for PricingTablePlanCost
        //private PricingTablePlanCost instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PricingTablePlanCost
            //instance = new PricingTablePlanCost();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PricingTablePlanCost
        /// </summary>
        [Test]
        public void PricingTablePlanCostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PricingTablePlanCost
            //Assert.IsInstanceOfType<PricingTablePlanCost> (instance, "variable 'instance' is a PricingTablePlanCost");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Per'
        /// </summary>
        [Test]
        public void PerTest()
        {
            // TODO unit test for the property 'Per'
        }
        /// <summary>
        /// Test the property 'Bill'
        /// </summary>
        [Test]
        public void BillTest()
        {
            // TODO unit test for the property 'Bill'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'CostText'
        /// </summary>
        [Test]
        public void CostTextTest()
        {
            // TODO unit test for the property 'CostText'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

    }

}
