/* 
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserConfigTests
    {
        // TODO uncomment below to declare an instance variable for UserConfig
        //private UserConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserConfig
            //instance = new UserConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserConfig
        /// </summary>
        [Test]
        public void UserConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserConfig
            //Assert.IsInstanceOfType<UserConfig> (instance, "variable 'instance' is a UserConfig");
        }

        /// <summary>
        /// Test the property 'AccountAutoApprove'
        /// </summary>
        [Test]
        public void AccountAutoApproveTest()
        {
            // TODO unit test for the property 'AccountAutoApprove'
        }
        /// <summary>
        /// Test the property 'LoginExpirationMin'
        /// </summary>
        [Test]
        public void LoginExpirationMinTest()
        {
            // TODO unit test for the property 'LoginExpirationMin'
        }

    }

}
